"use client";
import { useQuery } from "@tanstack/react-query";
import { fetchAPI } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Disclaimer } from "@/components/disclaimer";
import { Loader2, Download, RefreshCw, Sparkles } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface ReportData {
  report: string;
  generated_at: string;
  disclaimer: string;
}

export default function ReportPage() {
  const { data, isLoading, refetch, isFetching } = useQuery({
    queryKey: ["full-report"],
    queryFn: () => fetchAPI<ReportData>("/api/insights/full-report"),
    staleTime: 10 * 60 * 1000, // Cache 10 min
  });

  function handleDownload() {
    if (!data?.report) return;
    const blob = new Blob([data.report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `rva-contract-report-${new Date().toISOString().split("T")[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <Sparkles className="h-7 w-7 text-blue-600" aria-hidden="true" />
          AI Executive Report
        </h1>
        <p className="text-slate-500 mt-1">
          Comprehensive analysis across all 4 contract sources, generated by AI.
        </p>
      </div>

      <Disclaimer />

      {isLoading ? (
        <Card className="p-12 text-center">
          <Loader2 className="h-10 w-10 animate-spin text-blue-600 mx-auto mb-4" aria-hidden="true" />
          <p className="text-lg font-medium">Generating report...</p>
          <p className="text-sm text-slate-500 mt-1">
            AI is analyzing 1,395 contracts across City, Federal, State, and VITA sources.
          </p>
        </Card>
      ) : data?.report ? (
        <>
          {/* Actions */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="text-xs gap-1">
                <Sparkles className="h-3 w-3" aria-hidden="true" />
                AI-Generated
              </Badge>
              {data.generated_at && (
                <span className="text-xs text-slate-400">
                  Generated {new Date(data.generated_at).toLocaleString()}
                </span>
              )}
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => refetch()} disabled={isFetching} className="gap-1.5">
                <RefreshCw className={`h-3.5 w-3.5 ${isFetching ? "animate-spin" : ""}`} aria-hidden="true" />
                Regenerate
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5">
                <Download className="h-3.5 w-3.5" aria-hidden="true" />
                Download .md
              </Button>
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-1.5">
                <Download className="h-3.5 w-3.5" aria-hidden="true" />
                Print / PDF
              </Button>
            </div>
          </div>

          {/* Report Content */}
          <Card className="p-8">
            <article className="prose prose-slate dark:prose-invert max-w-none prose-headings:text-slate-900 dark:prose-headings:text-slate-100 prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg prose-p:leading-relaxed prose-li:leading-relaxed prose-strong:text-slate-900 dark:prose-strong:text-slate-100">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{data.report}</ReactMarkdown>
            </article>
          </Card>

          <p className="text-xs text-slate-400 text-center">{data.disclaimer}</p>
        </>
      ) : (
        <Card className="p-8 text-center">
          <p className="text-slate-500">Could not generate report. Please try again.</p>
          <Button onClick={() => refetch()} className="mt-4 gap-2">
            <RefreshCw className="h-4 w-4" aria-hidden="true" />
            Retry
          </Button>
        </Card>
      )}
    </div>
  );
}
